# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Terrell F. Merritt
email: terrell@terrellfmerritt.com
description: > # this means to ignore newlines until "url:"
  A college student, public relations practitioner, programmer, transit
  advocate, and passionate volunteer trying to do his part to help the community
  grow.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with
  <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

url:  http://terrellfmerritt.com # the base hostname & protocol for your site
baseurl: /tfm-alfolio/ # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: terrellfmerritt # put your github username
twitter_username: terrellfmerritt # put your twitter username
linkedin_username: terrellfmerritt # put your linkedin username
facebook_username: terrellfmerritt # put your facebook username
scholar_authorid: # put your google scholar author id
contact_note: Reach out to me on social media @terrellfmerritt or email me at
              [first_name]@[social_media_handle].com!
              # You can even add a little note about which of these is the best
              # way to reach you.

google_analytics: UA-56296585-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: terlmi
blog_description: a journey towards understanding my many passions

# Pagination
paginate: 4
permalink: /blog/:title/
paginate_path: /blog/:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: terlmi # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  orgs:
    output: true
    permalink: /orgs/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll-scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Merritt

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
